version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8090:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: marcelouser
      WORDPRESS_DB_PASSWORD: marcelopass
      WORDPRESS_DB_NAME: marcelodb
    volumes:
      - ./wp:/var/www/html

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: marcelodb
      MYSQL_USER: marcelouser
      MYSQL_PASSWORD: marcelopass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  db: